// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-angular/components/friends-list.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { OASISService } from '../services/oasis.service';

@Component({
  selector: 'oasis-friends-list',
  template: `
    <div class="oasis-friends-list" [class.oasis-friends-list--dark]="theme === 'dark'">
      <div class="friends-header">
        <h3>Friends ({{ (friends$ | async)?.length || 0 }})</h3>
        <input type="text" 
               placeholder="Search friends..."
               [(ngModel)]="searchQuery"
               (ngModelChange)="filterFriends()" />
      </div>

      <div class="friends-list">
        <div *ngIf="loading">Loading friends...</div>
        <div *ngFor="let friend of filteredFriends$ | async" class="friend-item">
          <img [src]="friend.image || '/default-avatar.png'" [alt]="friend.username" />
          <div class="friend-info">
            <h4>{{ friend.username }}</h4>
            <span *ngIf="showOnlineStatus" 
                  [class]="'status ' + (friend.isOnline ? 'online' : 'offline')">
              {{ friend.isOnline ? '🟢 Online' : '⚫ Offline' }}
            </span>
            <p class="karma">Karma: {{ friend.karma || 0 }}</p>
          </div>
          <div class="friend-actions" *ngIf="enableManagement">
            <button class="message-btn">💬</button>
            <button class="remove-btn" (click)="handleRemove(friend.id)">✕</button>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .friend-item {
      display: flex;
      align-items: center;
      gap: 1rem;
      padding: 1rem;
      border: 1px solid #ddd;
      border-radius: 8px;
      margin-bottom: 0.5rem;
    }
    .friend-item img { width: 50px; height: 50px; border-radius: 50%; }
  `]
})
export class OasisFriendsListComponent implements OnInit {
  @Input() avatarId!: string;
  @Input() theme: 'light' | 'dark' = 'dark';
  @Input() showOnlineStatus = true;
  @Input() enableManagement = true;

  friends$!: Observable<any[]>;
  filteredFriends$!: Observable<any[]>;
  searchQuery = '';
  loading = false;

  constructor(private oasisService: OASISService) {}

  ngOnInit() {
    this.friends$ = this.oasisService.getFriends(this.avatarId);
    this.filteredFriends$ = this.friends$;
  }

  filterFriends() {
    // Implement filtering logic
  }

  async handleRemove(friendId: string) {
    await this.oasisService.removeFriend(this.avatarId, friendId);
    this.friends$ = this.oasisService.getFriends(this.avatarId);
    this.filteredFriends$ = this.friends$;
  }
}

// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-vue/components/FriendsList.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { OASISClient } from '@oasis/api-client';

interface Props {
  avatarId: string;
  theme?: 'light' | 'dark';
}

const props = withDefaults(defineProps<Props>(), {
  theme: 'dark'
});

const emit = defineEmits<{
  select: [friend: any];
}>();

const friends = ref<any[]>([]);
const loading = ref(false);
const client = new OASISClient();

onMounted(async () => {
  await loadFriends();
});

async function loadFriends() {
  loading.value = true;
  try {
    friends.value = await client.getFriends(props.avatarId);
  } finally {
    loading.value = false;
  }
}

function selectFriend(friend: any) {
  emit('select', friend);
}
</script>

<template>
  <div class="oasis-friends-list" :class="[`oasis-friends-list--${theme}`]">
    <h3>Friends</h3>

    <div v-if="loading" class="loading">Loading friends...</div>

    <div v-else class="friends">
      <div
        v-for="friend in friends"
        :key="friend.id"
        class="friend-item"
        @click="selectFriend(friend)"
      >
        <img :src="friend.image" :alt="friend.username" class="friend-avatar" />
        <div class="friend-info">
          <h4>{{ friend.username }}</h4>
          <p>{{ friend.status || 'Online' }}</p>
        </div>
        <div class="friend-karma">{{ friend.karma }} 🏆</div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.oasis-friends-list {
  padding: 1.5rem;
  background: white;
  color: #333;
  border-radius: 12px;
}

.oasis-friends-list--dark {
  background: #1a1a1a;
  color: white;
}

.friends {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.friend-item {
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 0.75rem;
  background: #f5f5f5;
  border-radius: 8px;
  cursor: pointer;
  transition: background 0.2s;
}

.oasis-friends-list--dark .friend-item {
  background: #2a2a2a;
}

.friend-item:hover {
  background: rgba(0, 188, 212, 0.1);
}

.friend-avatar {
  width: 50px;
  height: 50px;
  border-radius: 50%;
}

.friend-info {
  flex: 1;
}

.friend-info h4 {
  margin: 0 0 0.25rem 0;
}

.friend-info p {
  margin: 0;
  font-size: 0.875rem;
  opacity: 0.7;
}

.friend-karma {
  font-weight: bold;
  color: #00bcd4;
}
</style>
