// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-react/components/FriendsList.tsx
import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from 'react-query';
import { OASISClient } from '@oasis/api-client';

export interface FriendsListProps {
  avatarId: string;
  theme?: 'light' | 'dark';
  showOnlineStatus?: boolean;
  enableManagement?: boolean;
  customStyles?: React.CSSProperties;
}

export const FriendsList: React.FC<FriendsListProps> = ({
  avatarId,
  theme = 'dark',
  showOnlineStatus = true,
  enableManagement = true,
  customStyles = {}
}) => {
  const [searchQuery, setSearchQuery] = useState('');
  const queryClient = useQueryClient();
  const client = new OASISClient();

  const { data: friends, isLoading } = useQuery(
    ['friends', avatarId],
    () => client.getFriends(avatarId)
  );

  const removeMutation = useMutation(
    (friendId: string) => client.removeFriend(avatarId, friendId),
    {
      onSuccess: () => {
        queryClient.invalidateQueries(['friends']);
      }
    }
  );

  const filteredFriends = friends?.filter((friend: any) =>
    friend.username.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className={`oasis-friends-list oasis-friends-list--${theme}`} style={customStyles}>
      <div className="friends-header">
        <h3>Friends ({friends?.length || 0})</h3>
        <input
          type="text"
          placeholder="Search friends..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
        />
      </div>

      <div className="friends-list">
        {isLoading ? (
          <div className="loading">Loading friends...</div>
        ) : (
          filteredFriends?.map((friend: any) => (
            <div key={friend.id} className="friend-item">
              <img src={friend.image || '/default-avatar.png'} alt={friend.username} />
              <div className="friend-info">
                <h4>{friend.username}</h4>
                {showOnlineStatus && (
                  <span className={`status ${friend.isOnline ? 'online' : 'offline'}`}>
                    {friend.isOnline ? '🟢 Online' : '⚫ Offline'}
                  </span>
                )}
                <p className="karma">Karma: {friend.karma || 0}</p>
              </div>
              {enableManagement && (
                <div className="friend-actions">
                  <button className="message-btn">💬</button>
                  <button 
                    className="remove-btn"
                    onClick={() => removeMutation.mutate(friend.id)}
                  >
                    ✕
                  </button>
                </div>
              )}
            </div>
          ))
        )}
      </div>
    </div>
  );
};

export default FriendsList;

// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-angular/components/friends-list.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { OASISService } from '../services/oasis.service';

@Component({
  selector: 'oasis-friends-list',
  template: `
    <div class="oasis-friends-list" [class.oasis-friends-list--dark]="theme === 'dark'">
      <div class="friends-header">
        <h3>Friends ({{ (friends$ | async)?.length || 0 }})</h3>
        <input type="text" 
               placeholder="Search friends..."
               [(ngModel)]="searchQuery"
               (ngModelChange)="filterFriends()" />
      </div>

      <div class="friends-list">
        <div *ngIf="loading">Loading friends...</div>
        <div *ngFor="let friend of filteredFriends$ | async" class="friend-item">
          <img [src]="friend.image || '/default-avatar.png'" [alt]="friend.username" />
          <div class="friend-info">
            <h4>{{ friend.username }}</h4>
            <span *ngIf="showOnlineStatus" 
                  [class]="'status ' + (friend.isOnline ? 'online' : 'offline')">
              {{ friend.isOnline ? '🟢 Online' : '⚫ Offline' }}
            </span>
            <p class="karma">Karma: {{ friend.karma || 0 }}</p>
          </div>
          <div class="friend-actions" *ngIf="enableManagement">
            <button class="message-btn">💬</button>
            <button class="remove-btn" (click)="handleRemove(friend.id)">✕</button>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .friend-item {
      display: flex;
      align-items: center;
      gap: 1rem;
      padding: 1rem;
      border: 1px solid #ddd;
      border-radius: 8px;
      margin-bottom: 0.5rem;
    }
    .friend-item img { width: 50px; height: 50px; border-radius: 50%; }
  `]
})
export class OasisFriendsListComponent implements OnInit {
  @Input() avatarId!: string;
  @Input() theme: 'light' | 'dark' = 'dark';
  @Input() showOnlineStatus = true;
  @Input() enableManagement = true;

  friends$!: Observable<any[]>;
  filteredFriends$!: Observable<any[]>;
  searchQuery = '';
  loading = false;

  constructor(private oasisService: OASISService) {}

  ngOnInit() {
    this.friends$ = this.oasisService.getFriends(this.avatarId);
    this.filteredFriends$ = this.friends$;
  }

  filterFriends() {
    // Implement filtering logic
  }

  async handleRemove(friendId: string) {
    await this.oasisService.removeFriend(this.avatarId, friendId);
    this.friends$ = this.oasisService.getFriends(this.avatarId);
    this.filteredFriends$ = this.friends$;
  }
}
