// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-angular/components/notifications.component.ts
import { Component, Input, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';
import { OASISService } from '../services/oasis.service';

@Component({
  selector: 'oasis-notifications',
  template: `
    <div class="oasis-notifications oasis-notifications--{{position}} oasis-notifications--{{theme}}">
      <div *ngFor="let notification of notifications"
           [class]="'notification notification--' + (notification.type || 'info')">
        <div class="notification-content">
          <h4>{{ notification.title }}</h4>
          <p>{{ notification.message }}</p>
        </div>
        <button class="dismiss-btn" (click)="handleDismiss(notification.id)">×</button>
      </div>
    </div>
  `,
  styles: [`
    .oasis-notifications {
      position: fixed;
      z-index: 9999;
      max-width: 400px;
    }
    .oasis-notifications--top-right { top: 20px; right: 20px; }
    .oasis-notifications--top-left { top: 20px; left: 20px; }
    .notification {
      background: white;
      padding: 1rem;
      margin-bottom: 0.5rem;
      border-radius: 8px;
      box-shadow: 0 4px 12px rgba(0,0,0,0.15);
      display: flex;
      justify-content: space-between;
      align-items: start;
    }
  `]
})
export class OasisNotificationsComponent implements OnInit, OnDestroy {
  @Input() avatarId!: string;
  @Input() position: 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left' = 'top-right';
  @Input() autoHide = true;
  @Input() duration = 5000;
  @Input() theme: 'light' | 'dark' = 'dark';

  notifications: any[] = [];
  private subscription?: Subscription;

  constructor(private oasisService: OASISService) {}

  ngOnInit() {
    this.subscription = this.oasisService.subscribeToNotifications(this.avatarId).subscribe(
      (notification: any) => {
        this.notifications.unshift(notification);
        
        if (this.autoHide) {
          setTimeout(() => {
            this.handleDismiss(notification.id);
          }, this.duration);
        }
      }
    );
  }

  ngOnDestroy() {
    this.subscription?.unsubscribe();
  }

  handleDismiss(id: string) {
    this.notifications = this.notifications.filter(n => n.id !== id);
  }
}

// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-react/components/Notifications.tsx
import React, { useEffect, useState } from 'react';
import { OASISClient } from '@oasis/api-client';

export interface NotificationsProps {
  avatarId: string;
  position?: 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left';
  autoHide?: boolean;
  duration?: number;
  theme?: 'light' | 'dark';
  customStyles?: React.CSSProperties;
}

export const Notifications: React.FC<NotificationsProps> = ({
  avatarId,
  position = 'top-right',
  autoHide = true,
  duration = 5000,
  theme = 'dark',
  customStyles = {}
}) => {
  const [notifications, setNotifications] = useState<any[]>([]);
  const client = new OASISClient();

  useEffect(() => {
    const unsubscribe = client.subscribeToNotifications(avatarId, (notification: any) => {
      setNotifications(prev => [notification, ...prev]);
      
      if (autoHide) {
        setTimeout(() => {
          setNotifications(prev => prev.filter(n => n.id !== notification.id));
        }, duration);
      }
    });

    return () => unsubscribe();
  }, [avatarId, autoHide, duration]);

  const handleDismiss = (id: string) => {
    setNotifications(prev => prev.filter(n => n.id !== id));
  };

  return (
    <div 
      className={`oasis-notifications oasis-notifications--${position} oasis-notifications--${theme}`}
      style={customStyles}
    >
      {notifications.map(notification => (
        <div 
          key={notification.id}
          className={`notification notification--${notification.type || 'info'}`}
        >
          <div className="notification-content">
            <h4>{notification.title}</h4>
            <p>{notification.message}</p>
          </div>
          <button 
            className="dismiss-btn"
            onClick={() => handleDismiss(notification.id)}
          >
            ×
          </button>
        </div>
      ))}
    </div>
  );
};

export default Notifications;
