// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-angular/components/karma-management.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { OASISService } from '../services/oasis.service';

@Component({
  selector: 'oasis-karma-management',
  template: `
    <div class="oasis-karma" [class.oasis-karma--dark]="theme === 'dark'">
      <div class="oasis-karma__current">
        <h3>Karma Points</h3>
        <div class="oasis-karma__value" *ngIf="karma$ | async as karma">
          {{ karma.total || 0 }}
        </div>
      </div>

      <div class="oasis-karma__history" *ngIf="showHistory && (history$ | async) as history">
        <h4>Recent Activity</h4>
        <ul>
          <li *ngFor="let entry of history">
            <span class="karma-amount">{{ entry.amount > 0 ? '+' : '' }}{{ entry.amount }}</span>
            <span class="karma-reason">{{ entry.reason }}</span>
            <span class="karma-date">{{ entry.date | date:'short' }}</span>
          </li>
        </ul>
      </div>

      <div class="oasis-karma__stats" *ngIf="karma$ | async as karma">
        <div class="stat">
          <span class="label">Rank</span>
          <span class="value">#{{ karma.rank || '-' }}</span>
        </div>
        <div class="stat">
          <span class="label">Level</span>
          <span class="value">{{ karma.level || 1 }}</span>
        </div>
        <div class="stat">
          <span class="label">Next Level</span>
          <span class="value">{{ karma.nextLevelAt || '-' }}</span>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .oasis-karma {
      padding: 1.5rem;
      background: #f5f5f5;
      border-radius: 12px;
    }
    .oasis-karma--dark {
      background: #1a1a1a;
      color: white;
    }
    .oasis-karma__value {
      font-size: 3rem;
      font-weight: bold;
      color: #00bcd4;
    }
  `]
})
export class OasisKarmaManagementComponent implements OnInit {
  @Input() avatarId!: string;
  @Input() theme: 'light' | 'dark' = 'dark';
  @Input() showHistory = true;

  karma$!: Observable<any>;
  history$!: Observable<any[]>;

  constructor(private oasisService: OASISService) {}

  ngOnInit() {
    this.karma$ = this.oasisService.getAvatarKarma(this.avatarId);
    if (this.showHistory) {
      this.history$ = this.oasisService.getKarmaHistory(this.avatarId);
    }
  }
}

// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-react/components/KarmaManagement.tsx
import React, { useEffect, useState } from 'react';
import { useQuery } from 'react-query';
import { OASISClient } from '@oasis/api-client';

export interface KarmaManagementProps {
  avatarId: string;
  theme?: 'light' | 'dark';
  showLeaderboard?: boolean;
  showHistory?: boolean;
  customStyles?: React.CSSProperties;
}

export const KarmaManagement: React.FC<KarmaManagementProps> = ({
  avatarId,
  theme = 'dark',
  showLeaderboard = true,
  showHistory = true,
  customStyles = {}
}) => {
  const client = new OASISClient();

  const { data: karma, isLoading } = useQuery(
    ['karma', avatarId],
    () => client.getAvatarKarma(avatarId)
  );

  const { data: history } = useQuery(
    ['karma-history', avatarId],
    () => client.getKarmaHistory(avatarId),
    { enabled: showHistory }
  );

  return (
    <div className={`oasis-karma oasis-karma--${theme}`} style={customStyles}>
      <div className="oasis-karma__current">
        <h3>Karma Points</h3>
        {isLoading ? (
          <div className="oasis-karma__loading">Loading...</div>
        ) : (
          <div className="oasis-karma__value">{karma?.total || 0}</div>
        )}
      </div>

      {showHistory && history && (
        <div className="oasis-karma__history">
          <h4>Recent Activity</h4>
          <ul>
            {history.map((entry: any) => (
              <li key={entry.id}>
                <span className="karma-amount">{entry.amount > 0 ? '+' : ''}{entry.amount}</span>
                <span className="karma-reason">{entry.reason}</span>
                <span className="karma-date">{new Date(entry.date).toLocaleDateString()}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <div className="oasis-karma__stats">
        <div className="stat">
          <span className="label">Rank</span>
          <span className="value">#{karma?.rank || '-'}</span>
        </div>
        <div className="stat">
          <span className="label">Level</span>
          <span className="value">{karma?.level || 1}</span>
        </div>
        <div className="stat">
          <span className="label">Next Level</span>
          <span className="value">{karma?.nextLevelAt || '-'}</span>
        </div>
      </div>
    </div>
  );
};

export default KarmaManagement;
