// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-react/components/KarmaLeaderboard.tsx
import React from 'react';
import { useQuery } from 'react-query';
import { OASISClient } from '@oasis/api-client';

export interface KarmaLeaderboardProps {
  limit?: number;
  timeRange?: 'day' | 'week' | 'month' | 'all';
  highlightCurrentUser?: boolean;
  currentAvatarId?: string;
  theme?: 'light' | 'dark';
  customStyles?: React.CSSProperties;
}

export const KarmaLeaderboard: React.FC<KarmaLeaderboardProps> = ({
  limit = 10,
  timeRange = 'week',
  highlightCurrentUser = true,
  currentAvatarId,
  theme = 'dark',
  customStyles = {}
}) => {
  const client = new OASISClient();

  const { data: leaderboard, isLoading } = useQuery(
    ['karma-leaderboard', timeRange, limit],
    () => client.getKarmaLeaderboard(timeRange, limit)
  );

  const getMedalEmoji = (rank: number) => {
    if (rank === 1) return '🥇';
    if (rank === 2) return '🥈';
    if (rank === 3) return '🥉';
    return `#${rank}`;
  };

  return (
    <div className={`oasis-karma-leaderboard oasis-karma-leaderboard--${theme}`} style={customStyles}>
      <div className="leaderboard-header">
        <h3>Karma Leaderboard</h3>
        <span className="time-range">{timeRange.charAt(0).toUpperCase() + timeRange.slice(1)}</span>
      </div>

      <div className="leaderboard-list">
        {isLoading ? (
          <div className="loading">Loading leaderboard...</div>
        ) : (
          leaderboard?.map((entry: any, index: number) => (
            <div 
              key={entry.avatarId}
              className={`leaderboard-item ${
                highlightCurrentUser && entry.avatarId === currentAvatarId ? 'current-user' : ''
              }`}
            >
              <span className="rank">{getMedalEmoji(index + 1)}</span>
              <img 
                src={entry.avatarImage || '/default-avatar.png'} 
                alt={entry.username}
                className="avatar"
              />
              <div className="user-info">
                <h4>{entry.username}</h4>
                <span className="level">Level {entry.level}</span>
              </div>
              <div className="karma-score">
                <span className="value">{entry.karma.toLocaleString()}</span>
                <span className="label">karma</span>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};

export default KarmaLeaderboard;

// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-vue/components/KarmaLeaderboard.vue
<template>
  <div :class="['oasis-karma-leaderboard', `oasis-karma-leaderboard--${theme}`]">
    <div class="leaderboard-header">
      <h3>Karma Leaderboard</h3>
      <span class="time-range">{{ timeRange.charAt(0).toUpperCase() + timeRange.slice(1) }}</span>
    </div>

    <div class="leaderboard-list">
      <div v-if="loading">Loading leaderboard...</div>
      <div 
        v-for="(entry, index) in leaderboard" 
        :key="entry.avatarId"
        :class="['leaderboard-item', { 'current-user': highlightCurrentUser && entry.avatarId === currentAvatarId }]">
        <span class="rank">{{ getMedalEmoji(index + 1) }}</span>
        <img :src="entry.avatarImage || '/default-avatar.png'" :alt="entry.username" class="avatar" />
        <div class="user-info">
          <h4>{{ entry.username }}</h4>
          <span class="level">Level {{ entry.level }}</span>
        </div>
        <div class="karma-score">
          <span class="value">{{ entry.karma.toLocaleString() }}</span>
          <span class="label">karma</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { OASISClient } from '@oasis/api-client';

interface Props {
  limit?: number;
  timeRange?: 'day' | 'week' | 'month' | 'all';
  highlightCurrentUser?: boolean;
  currentAvatarId?: string;
  theme?: 'light' | 'dark';
}

const props = withDefaults(defineProps<Props>(), {
  limit: 10,
  timeRange: 'week',
  highlightCurrentUser: true,
  theme: 'dark'
});

const leaderboard = ref<any[]>([]);
const loading = ref(false);
const client = new OASISClient();

onMounted(async () => {
  loading.value = true;
  leaderboard.value = await client.getKarmaLeaderboard(props.timeRange, props.limit);
  loading.value = false;
});

const getMedalEmoji = (rank: number): string => {
  if (rank === 1) return '🥇';
  if (rank === 2) return '🥈';
  if (rank === 3) return '🥉';
  return `#${rank}`;
};
</script>

<style scoped>
.leaderboard-item { display: flex; align-items: center; gap: 1rem; padding: 1rem; border: 1px solid #ddd; border-radius: 8px; margin-bottom: 0.5rem; }
.leaderboard-item.current-user { background-color: #e3f2fd; }
.avatar { width: 40px; height: 40px; border-radius: 50%; }
</style>
