// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-angular/components/nft-gallery.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { OASISService } from '../services/oasis.service';

@Component({
  selector: 'oasis-nft-gallery',
  template: `
    <div class="oasis-nft-gallery" [class.oasis-nft-gallery--dark]="theme === 'dark'">
      <div class="gallery-controls" *ngIf="enableFilters">
        <select [(ngModel)]="selectedFilter" (change)="filterNFTs()">
          <option value="all">All Collections</option>
          <option *ngFor="let col of collections" [value]="col">{{ col }}</option>
        </select>
        <select [(ngModel)]="selectedSort" (change)="sortNFTs()">
          <option value="date">Sort by Date</option>
          <option value="price">Sort by Price</option>
          <option value="name">Sort by Name</option>
        </select>
      </div>

      <div class="nft-grid" [style.grid-template-columns]="'repeat(' + columns + ', 1fr)'">
        <div *ngIf="loading" class="loading">Loading NFTs...</div>
        <div *ngFor="let nft of filteredNFTs$ | async" 
             class="nft-item"
             (click)="onSelect.emit(nft)">
          <img [src]="nft.imageUrl" [alt]="nft.name" />
          <div class="nft-info">
            <h4>{{ nft.name }}</h4>
            <p class="collection">{{ nft.collection }}</p>
            <p class="price">{{ nft.price }} OASIS</p>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .nft-grid { display: grid; gap: 1rem; }
    .nft-item { cursor: pointer; border: 1px solid #ddd; border-radius: 8px; overflow: hidden; }
    .nft-item img { width: 100%; height: 200px; object-fit: cover; }
  `]
})
export class OasisNFTGalleryComponent implements OnInit {
  @Input() avatarId?: string;
  @Input() collections: string[] = [];
  @Input() columns = 3;
  @Input() theme: 'light' | 'dark' = 'dark';
  @Input() enableFilters = true;
  @Input() sortBy: 'date' | 'price' | 'name' = 'date';
  @Output() onSelect = new EventEmitter<any>();

  filteredNFTs$!: Observable<any[]>;
  loading = false;
  selectedFilter = 'all';
  selectedSort = this.sortBy;

  constructor(private oasisService: OASISService) {}

  ngOnInit() {
    this.filteredNFTs$ = this.oasisService.getNFTs(this.avatarId, this.collections);
  }

  filterNFTs() {
    // Implement filtering logic
  }

  sortNFTs() {
    // Implement sorting logic
  }
}

// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-vue/components/NFTGallery.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { OASISClient } from '@oasis/api-client';

interface Props {
  avatarId: string;
  columns?: number;
  theme?: 'light' | 'dark';
}

const props = withDefaults(defineProps<Props>(), {
  columns: 3,
  theme: 'dark'
});

const emit = defineEmits<{
  select: [nft: any];
}>();

const nfts = ref<any[]>([]);
const loading = ref(false);
const client = new OASISClient();

onMounted(async () => {
  await loadNFTs();
});

async function loadNFTs() {
  loading.value = true;
  try {
    nfts.value = await client.getNFTs(props.avatarId);
  } finally {
    loading.value = false;
  }
}

function selectNFT(nft: any) {
  emit('select', nft);
}
</script>

<template>
  <div class="oasis-nft-gallery" :class="[`oasis-nft-gallery--${theme}`]">
    <div v-if="loading" class="loading">Loading NFTs...</div>
    
    <div
      v-else
      class="nft-grid"
      :style="{ gridTemplateColumns: `repeat(${columns}, 1fr)` }"
    >
      <div
        v-for="nft in nfts"
        :key="nft.id"
        class="nft-item"
        @click="selectNFT(nft)"
      >
        <img :src="nft.imageUrl" :alt="nft.name" class="nft-image" />
        <div class="nft-info">
          <h4 class="nft-name">{{ nft.name }}</h4>
          <p v-if="nft.collection" class="nft-collection">{{ nft.collection }}</p>
          <p class="nft-price">{{ nft.price || 0 }} OASIS</p>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.oasis-nft-gallery {
  padding: 1rem;
}

.nft-grid {
  display: grid;
  gap: 1rem;
}

.nft-item {
  background: white;
  border: 1px solid #ddd;
  border-radius: 8px;
  overflow: hidden;
  cursor: pointer;
  transition: transform 0.2s;
}

.oasis-nft-gallery--dark .nft-item {
  background: #2a2a2a;
  border-color: #3a3a3a;
  color: white;
}

.nft-item:hover {
  transform: translateY(-4px);
}

.nft-image {
  width: 100%;
  height: 200px;
  object-fit: cover;
}

.nft-info {
  padding: 1rem;
}

.nft-name {
  font-weight: bold;
  margin: 0 0 0.5rem 0;
}

.nft-collection {
  font-size: 0.875rem;
  opacity: 0.7;
  margin: 0 0 0.5rem 0;
}

.nft-price {
  color: #00bcd4;
  font-weight: bold;
  margin: 0;
}

.loading {
  text-align: center;
  padding: 2rem;
}
</style>
