// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-nextjs/components/OASISProvider.tsx
import { createContext, useContext, ReactNode } from 'react';
import axios from 'axios';

interface OASISContextType {
  client: any;
  isAuthenticated: boolean;
}

const OASISContext = createContext<OASISContextType | undefined>(undefined);

interface OASISProviderProps {
  children: ReactNode;
  apiUrl: string;
  apiKey?: string;
}

export function OASISProvider({ children, apiUrl, apiKey }: OASISProviderProps) {
  const client = axios.create({
    baseURL: apiUrl,
    headers: apiKey ? { 'X-API-Key': apiKey } : {}
  });

  return (
    <OASISContext.Provider value={{ client, isAuthenticated: false }}>
      {children}
    </OASISContext.Provider>
  );
}

export function useOASIS() {
  const context = useContext(OASISContext);
  if (!context) {
    throw new Error('useOASIS must be used within OASISProvider');
  }
  return context;
}

// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-vue/components/OASISProvider.vue
<template>
  <slot :client="client" :isAuthenticated="isAuthenticated" :user="user" />
</template>

<script setup lang="ts">
import { ref, provide } from 'vue';
import axios from 'axios';

const props = defineProps<{ apiUrl: string; apiKey?: string }>();

const client = ref(axios.create({ baseURL: props.apiUrl, headers: props.apiKey ? { 'X-API-Key': props.apiKey } : {} }));
const isAuthenticated = ref(false);
const user = ref(null);

provide('oasisClient', client);
provide('oasisAuth', { isAuthenticated, user });
</script>
