// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-nextjs/components/DataManagement.tsx
import { useState, useEffect } from 'react';
import { useOASIS } from '../hooks/useOASIS';

export default function DataManagement() {
  const { client } = useOASIS();
  const [holons, setHolons] = useState([]);
  const [name, setName] = useState('');
  const [holonType, setHolonType] = useState('');

  useEffect(() => {
    loadHolons();
  }, []);

  async function loadHolons() {
    const response = await client.get('/api/data/holons');
    setHolons(response.data);
  }

  async function createHolon() {
    await client.post('/api/data/holons', { name, holonType });
    setName('');
    setHolonType('');
    loadHolons();
  }

  return (
    <div className="data-management">
      <div className="create-form">
        <input value={name} onChange={(e) => setName(e.target.value)} placeholder="Holon Name" />
        <input value={holonType} onChange={(e) => setHolonType(e.target.value)} placeholder="Type" />
        <button onClick={createHolon}>Create</button>
      </div>
      {holons.map((holon: any) => (
        <div key={holon.id} className="holon-card">
          <h3>{holon.name}</h3>
          <p>Type: {holon.holonType}</p>
        </div>
      ))}
      <style jsx>{`
        .create-form { display: flex; gap: 8px; margin-bottom: 20px; }
        input { flex: 1; padding: 10px; border: 1px solid #ddd; border-radius: 4px; }
        button { padding: 10px 20px; background: #27ae60; color: white; border: none; border-radius: 4px; cursor: pointer; }
        .holon-card { background: white; padding: 16px; margin-bottom: 12px; border-radius: 8px; }
      `}</style>
    </div>
  );
}

// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-svelte/components/DataManagement.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { oasisStore } from '../stores/oasis';

  let holons = [];
  let name = '';
  let holonType = '';

  onMount(async () => {
    const response = await $oasisStore.client.get('/api/data/holons');
    holons = response.data;
  });

  async function createHolon() {
    await $oasisStore.client.post('/api/data/holons', { name, holonType });
    name = '';
    holonType = '';
    const response = await $oasisStore.client.get('/api/data/holons');
    holons = response.data;
  }
</script>

<div class="data-management">
  <div class="create-form">
    <input bind:value={name} placeholder="Holon Name" />
    <input bind:value={holonType} placeholder="Type" />
    <button on:click={createHolon}>Create</button>
  </div>
  {#each holons as holon}
    <div class="holon-card">
      <h3>{holon.name}</h3>
      <p>Type: {holon.holonType}</p>
    </div>
  {/each}
</div>

<style>
  .create-form { display: flex; gap: 8px; margin-bottom: 20px; }
  input { flex: 1; padding: 10px; border: 1px solid #ddd; border-radius: 4px; }
  button { padding: 10px 20px; background: #27ae60; color: white; border: none; border-radius: 4px; cursor: pointer; }
  .holon-card { background: white; padding: 16px; margin-bottom: 12px; border-radius: 8px; }
</style>
