// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-vue/components/DataManagement.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { OASISClient } from '@oasis/api-client';

interface Props {
  avatarId: string;
  theme?: 'light' | 'dark';
}

const props = withDefaults(defineProps<Props>(), {
  theme: 'dark'
});

const data = ref<any[]>([]);
const loading = ref(false);
const newKey = ref('');
const newValue = ref('');
const client = new OASISClient();

onMounted(async () => {
  await loadData();
});

async function loadData() {
  loading.value = true;
  try {
    const result = await client.getData(props.avatarId);
    data.value = Object.entries(result).map(([key, value]) => ({ key, value }));
  } finally {
    loading.value = false;
  }
}

async function saveData() {
  if (!newKey.value || !newValue.value) return;

  try {
    await client.saveData(props.avatarId, newKey.value, newValue.value);
    newKey.value = '';
    newValue.value = '';
    await loadData();
  } catch (error) {
    console.error('Error saving data:', error);
  }
}

async function deleteData(key: string) {
  try {
    await client.deleteData(props.avatarId, key);
    await loadData();
  } catch (error) {
    console.error('Error deleting data:', error);
  }
}
</script>

<template>
  <div class="oasis-data-mgmt" :class="[`oasis-data-mgmt--${theme}`]">
    <h3>Data Management</h3>

    <div class="add-data">
      <input v-model="newKey" type="text" placeholder="Key" />
      <input v-model="newValue" type="text" placeholder="Value" />
      <button @click="saveData">Add</button>
    </div>

    <div v-if="loading" class="loading">Loading data...</div>

    <div v-else class="data-list">
      <div v-for="item in data" :key="item.key" class="data-item">
        <div class="data-key">{{ item.key }}</div>
        <div class="data-value">{{ item.value }}</div>
        <button class="delete-btn" @click="deleteData(item.key)">×</button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.oasis-data-mgmt {
  padding: 1.5rem;
  background: white;
  color: #333;
  border-radius: 12px;
}

.oasis-data-mgmt--dark {
  background: #1a1a1a;
  color: white;
}

.add-data {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
}

.add-data input {
  flex: 1;
  padding: 0.5rem;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.oasis-data-mgmt--dark .add-data input {
  background: #2a2a2a;
  border-color: #3a3a3a;
  color: white;
}

.add-data button {
  padding: 0.5rem 1rem;
  background: #00bcd4;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.data-list {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.data-item {
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 0.75rem;
  background: #f5f5f5;
  border-radius: 8px;
}

.oasis-data-mgmt--dark .data-item {
  background: #2a2a2a;
}

.data-key {
  font-weight: bold;
  min-width: 120px;
}

.data-value {
  flex: 1;
  opacity: 0.8;
}

.delete-btn {
  background: #f44336;
  color: white;
  border: none;
  border-radius: 50%;
  width: 24px;
  height: 24px;
  cursor: pointer;
  font-size: 1.2rem;
  line-height: 1;
}
</style>

// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-angular/components/data-management.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { OASISService } from '../services/oasis.service';

@Component({
  selector: 'oasis-data-management',
  template: `
    <div class="oasis-data-mgmt" [class.oasis-data-mgmt--dark]="theme === 'dark'">
      <div class="data-header">
        <h3>Data Management</h3>
        <div class="data-actions">
          <button *ngIf="enableExport" (click)="handleExport()">📥 Export</button>
          <button *ngIf="enableImport">📤 Import</button>
        </div>
      </div>

      <div class="data-create">
        <input type="text" placeholder="Key" [(ngModel)]="newKey" />
        <textarea placeholder="Value (JSON)" [(ngModel)]="newValue" rows="3"></textarea>
        <button (click)="handleSave()" [disabled]="saving">
          {{ saving ? 'Saving...' : 'Save Data' }}
        </button>
      </div>

      <div class="data-list">
        <div *ngIf="loading">Loading data...</div>
        <div *ngFor="let item of dataItems | keyvalue" class="data-item">
          <div class="data-key">{{ item.key }}</div>
          <div class="data-value">
            <pre>{{ item.value | json }}</pre>
          </div>
          <button class="delete-btn" (click)="handleDelete(item.key)">🗑️</button>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .data-item {
      display: flex;
      gap: 1rem;
      padding: 1rem;
      border: 1px solid #ddd;
      border-radius: 8px;
      margin-bottom: 1rem;
    }
    .data-value pre { margin: 0; }
  `]
})
export class OasisDataManagementComponent implements OnInit {
  @Input() avatarId!: string;
  @Input() theme: 'light' | 'dark' = 'dark';
  @Input() enableExport = true;
  @Input() enableImport = true;

  dataItems: any = {};
  newKey = '';
  newValue = '';
  loading = false;
  saving = false;

  constructor(private oasisService: OASISService) {}

  async ngOnInit() {
    this.loading = true;
    this.dataItems = await this.oasisService.getAvatarData(this.avatarId);
    this.loading = false;
  }

  async handleSave() {
    if (!this.newKey || !this.newValue) return;
    
    this.saving = true;
    try {
      await this.oasisService.saveData(this.avatarId, this.newKey, this.newValue);
      this.dataItems[this.newKey] = JSON.parse(this.newValue);
      this.newKey = '';
      this.newValue = '';
    } finally {
      this.saving = false;
    }
  }

  async handleDelete(key: string) {
    await this.oasisService.deleteData(this.avatarId, key);
    delete this.dataItems[key];
  }

  handleExport() {
    const dataStr = JSON.stringify(this.dataItems, null, 2);
    const blob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `oasis-data-${this.avatarId}.json`;
    link.click();
  }
}
