// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-react/components/GeoNFTMap.tsx
import React, { useEffect, useRef, useState } from 'react';
import { OASISClient } from '@oasis/api-client';

export interface GeoNFTMapProps {
  avatarId?: string;
  center?: { lat: number; lng: number };
  zoom?: number;
  theme?: 'light' | 'dark';
  enableCreation?: boolean;
  customStyles?: React.CSSProperties;
}

export const GeoNFTMap: React.FC<GeoNFTMapProps> = ({
  avatarId,
  center = { lat: 0, lng: 0 },
  zoom = 2,
  theme = 'dark',
  enableCreation = true,
  customStyles = {}
}) => {
  const mapRef = useRef<HTMLDivElement>(null);
  const [geoNFTs, setGeoNFTs] = useState<any[]>([]);
  const [selectedNFT, setSelectedNFT] = useState<any>(null);
  const client = new OASISClient();

  useEffect(() => {
    loadGeoNFTs();
  }, [avatarId]);

  const loadGeoNFTs = async () => {
    const result = await client.getGeoNFTs(avatarId);
    setGeoNFTs(result);
  };

  return (
    <div className={`oasis-geonft-map oasis-geonft-map--${theme}`} style={customStyles}>
      <div ref={mapRef} className="map-container" />
      
      <div className="map-controls">
        {enableCreation && (
          <button className="create-geonft-btn">
            📍 Create Geo-NFT
          </button>
        )}
      </div>

      {selectedNFT && (
        <div className="geonft-popup">
          <img src={selectedNFT.imageUrl} alt={selectedNFT.name} />
          <h4>{selectedNFT.name}</h4>
          <p>{selectedNFT.description}</p>
          <div className="location">
            📍 {selectedNFT.location.lat.toFixed(6)}, {selectedNFT.location.lng.toFixed(6)}
          </div>
        </div>
      )}
    </div>
  );
};

export default GeoNFTMap;

// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-angular/components/geonft-map.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { OASISService } from '../services/oasis.service';

@Component({
  selector: 'oasis-geonft-map',
  template: `
    <div class="oasis-geonft-map" [class.oasis-geonft-map--dark]="theme === 'dark'">
      <div #mapContainer class="map-container"></div>
      
      <div class="map-controls">
        <button *ngIf="enableCreation" class="create-geonft-btn">
          📍 Create Geo-NFT
        </button>
      </div>

      <div *ngIf="selectedNFT" class="geonft-popup">
        <img [src]="selectedNFT.imageUrl" [alt]="selectedNFT.name" />
        <h4>{{ selectedNFT.name }}</h4>
        <p>{{ selectedNFT.description }}</p>
        <div class="location">
          📍 {{ selectedNFT.location.lat | number:'1.6-6' }}, 
             {{ selectedNFT.location.lng | number:'1.6-6' }}
        </div>
      </div>
    </div>
  `,
  styles: [`
    .oasis-geonft-map { position: relative; height: 100%; }
    .map-container { width: 100%; height: 100%; }
    .map-controls { position: absolute; top: 10px; right: 10px; }
    .geonft-popup {
      position: absolute;
      bottom: 20px;
      left: 20px;
      background: white;
      padding: 1rem;
      border-radius: 8px;
      box-shadow: 0 4px 12px rgba(0,0,0,0.2);
      max-width: 300px;
    }
  `]
})
export class OasisGeoNFTMapComponent implements OnInit {
  @Input() avatarId?: string;
  @Input() center = { lat: 0, lng: 0 };
  @Input() zoom = 2;
  @Input() theme: 'light' | 'dark' = 'dark';
  @Input() enableCreation = true;
  @Output() onLocationSelect = new EventEmitter<any>();

  geoNFTs: any[] = [];
  selectedNFT: any = null;

  constructor(private oasisService: OASISService) {}

  async ngOnInit() {
    this.geoNFTs = await this.oasisService.getGeoNFTs(this.avatarId);
  }
}
