// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-nextjs/components/KarmaManagement.tsx
'use client';

import { useState, useEffect } from 'react';
import { OASISClient } from '@oasis/api-client';

interface KarmaManagementProps {
  avatarId: string;
  theme?: 'light' | 'dark';
  showHistory?: boolean;
}

export default function KarmaManagement({ 
  avatarId, 
  theme = 'dark',
  showHistory = true 
}: KarmaManagementProps) {
  const [karma, setKarma] = useState<any>(null);
  const [history, setHistory] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const client = new OASISClient();

  useEffect(() => {
    loadKarma();
  }, [avatarId]);

  const loadKarma = async () => {
    setLoading(true);
    try {
      const karmaData = await client.getAvatarKarma(avatarId);
      setKarma(karmaData);
      
      if (showHistory) {
        const historyData = await client.getKarmaHistory(avatarId);
        setHistory(historyData);
      }
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return <div className="loading">Loading karma...</div>;
  }

  return (
    <div className={`oasis-karma-mgmt oasis-karma-mgmt--${theme}`}>
      <div className="karma-current">
        <h3>Karma Points</h3>
        <div className="karma-value">{karma?.total || 0}</div>
      </div>

      {karma && (
        <div className="karma-stats">
          <div className="stat">
            <span className="label">Rank</span>
            <span className="value">#{karma.rank || '-'}</span>
          </div>
          <div className="stat">
            <span className="label">Level</span>
            <span className="value">{karma.level || 1}</span>
          </div>
          <div className="stat">
            <span className="label">Next Level</span>
            <span className="value">{karma.nextLevelAt || '-'}</span>
          </div>
        </div>
      )}

      {showHistory && history.length > 0 && (
        <div className="karma-history">
          <h4>Recent Activity</h4>
          <ul>
            {history.map((entry: any) => (
              <li key={entry.id}>
                <span className="reason">{entry.reason}</span>
                <span className={entry.amount > 0 ? 'positive' : 'negative'}>
                  {entry.amount > 0 ? '+' : ''}{entry.amount}
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <style jsx>{`
        .oasis-karma-mgmt {
          padding: 1.5rem;
          background: ${theme === 'dark' ? '#1a1a1a' : 'white'};
          color: ${theme === 'dark' ? 'white' : '#333'};
          border-radius: 12px;
        }
        .karma-current {
          text-align: center;
          margin-bottom: 1.5rem;
        }
        .karma-value {
          font-size: 3rem;
          font-weight: bold;
          color: #00bcd4;
        }
        .karma-stats {
          display: flex;
          justify-content: space-around;
          gap: 1rem;
          margin-bottom: 1.5rem;
        }
        .stat {
          text-align: center;
        }
        .stat .label {
          display: block;
          font-size: 0.875rem;
          opacity: 0.7;
        }
        .stat .value {
          font-size: 1.25rem;
          font-weight: bold;
        }
        .karma-history ul {
          list-style: none;
          padding: 0;
        }
        .karma-history li {
          display: flex;
          justify-content: space-between;
          padding: 0.5rem 0;
          border-bottom: 1px solid ${theme === 'dark' ? '#2a2a2a' : '#f5f5f5'};
        }
        .positive {
          color: #4caf50;
        }
        .negative {
          color: #f44336;
        }
      `}</style>
    </div>
  );
}

// STAR ODK/NextGenSoftware.OASIS.STAR.WebUI/ClientApp/public/downloads/oasis-webui-devkit-angular/components/karma-management.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { OASISService } from '../services/oasis.service';

@Component({
  selector: 'oasis-karma-management',
  template: `
    <div class="oasis-karma" [class.oasis-karma--dark]="theme === 'dark'">
      <div class="oasis-karma__current">
        <h3>Karma Points</h3>
        <div class="oasis-karma__value" *ngIf="karma$ | async as karma">
          {{ karma.total || 0 }}
        </div>
      </div>

      <div class="oasis-karma__history" *ngIf="showHistory && (history$ | async) as history">
        <h4>Recent Activity</h4>
        <ul>
          <li *ngFor="let entry of history">
            <span class="karma-amount">{{ entry.amount > 0 ? '+' : '' }}{{ entry.amount }}</span>
            <span class="karma-reason">{{ entry.reason }}</span>
            <span class="karma-date">{{ entry.date | date:'short' }}</span>
          </li>
        </ul>
      </div>

      <div class="oasis-karma__stats" *ngIf="karma$ | async as karma">
        <div class="stat">
          <span class="label">Rank</span>
          <span class="value">#{{ karma.rank || '-' }}</span>
        </div>
        <div class="stat">
          <span class="label">Level</span>
          <span class="value">{{ karma.level || 1 }}</span>
        </div>
        <div class="stat">
          <span class="label">Next Level</span>
          <span class="value">{{ karma.nextLevelAt || '-' }}</span>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .oasis-karma {
      padding: 1.5rem;
      background: #f5f5f5;
      border-radius: 12px;
    }
    .oasis-karma--dark {
      background: #1a1a1a;
      color: white;
    }
    .oasis-karma__value {
      font-size: 3rem;
      font-weight: bold;
      color: #00bcd4;
    }
  `]
})
export class OasisKarmaManagementComponent implements OnInit {
  @Input() avatarId!: string;
  @Input() theme: 'light' | 'dark' = 'dark';
  @Input() showHistory = true;

  karma$!: Observable<any>;
  history$!: Observable<any[]>;

  constructor(private oasisService: OASISService) {}

  ngOnInit() {
    this.karma$ = this.oasisService.getAvatarKarma(this.avatarId);
    if (this.showHistory) {
      this.history$ = this.oasisService.getKarmaHistory(this.avatarId);
    }
  }
}
